name: vibe_line
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  flutter_lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "lib/asset/image/AppLogo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/asset/image/

  fonts:
    - family: Kenia
      fonts:
        - asset: lib/asset/font/Kenia-Regular.ttf
    - family: Lato
      fonts:
        - asset: lib/asset/font/Lato-Black.ttf
